name: caffiene
description: A new Flutter project.

publish_to: "none"

version: 1.5.2-dev

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.1
  better_player:
    path: C:\Users\solox\Desktop\Projects\caffeine_betterplayer
  cached_network_image: ^3.2.2
  carousel_slider: ^4.1.1
  cast: ^1.1.1
  change_app_package_name: ^1.1.0
  clipboard: ^0.1.3
  cloud_firestore: ^4.5.3
  connectivity_plus: ^3.0.6
  cupertino_icons: ^1.0.2
  device_info_plus: ^8.2.2
  dio: ^4.0.6
  dynamic_color: ^1.6.3
  easy_localization: ^3.0.2
  ffmpeg_kit_flutter: ^5.1.0
  firebase_analytics: ^10.6.4
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_messaging: ^14.4.1
  firebase_remote_config: ^4.2.5
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_colorpicker: ^1.0.3
  flutter_dotenv: ^5.1.0
  flutter_download_manager: ^0.5.4
  flutter_downloader: ^1.10.2
  flutter_inappwebview: ^5.4.4+3
  flutter_launcher_icons: ^0.13.1
  flutter_localization: ^0.1.13
  flutter_rating_bar: ^4.0.1
  flutter_svg: null
  flutter_vlc_player: ^7.1.5
  fluttertoast: ^8.1.1
  font_awesome_flutter: ^10.2.1
  get: ^4.6.6
  google_fonts: ^4.0.4
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.1.0
  http: ^0.13.4
  image_fade: ^0.6.1
  intl: ^0.18.0
  lazyui: ^0.4.8
  mixpanel_flutter: ^2.1.1
  native_device_orientation: ^1.1.4
  need_resume: ^1.0.7+1
  open_file_plus: ^3.4.1
  path_provider: ^2.1.1
  percent_indicator: ^4.2.3
  permission_handler: ^11.0.1
  photo_view: ^0.14.0
  provider: ^6.0.3
  readmore: ^2.1.0
  retry: ^3.1.1
  rounded_loading_button: ^2.1.0
  scrollable_positioned_list: ^0.3.5
  share_plus: ^6.3.4
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  sizer: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  sqflite: ^2.2.8
  startapp_sdk: ^0.4.2
  supabase_flutter: ^1.10.22
  transparent_image: ^2.0.0
  url_launcher: ^6.1.6
  wakelock: ^0.6.2
  web_scraper: ^0.1.4


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/ca/
    - assets/translations/
    - assets/images/
    - assets/images/profiles/
    - assets/images/country_flags/
    - assets/icons/
    - assets/movixIcon/
    - assets/Bold/
    - assets/gif/
    - assets/gpay.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
    - family: PoppinsSB
      fonts:
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
    - family: SocialIcons
      fonts:
        - asset: assets/fonts/SocialIcons.ttf
    - family: IMdb
      fonts:
        - asset: assets/fonts/imdb.ttf
