import 'dart:io';

/// Reads version from pubspec.yaml and writes lib/utils/app_version.g.dart.
/// Run from project root: dart run tool/version_gen.dart
void main() {
  final pubspec = File('pubspec.yaml');
  if (!pubspec.existsSync()) {
    stderr.writeln('pubspec.yaml not found. Run from project root.');
    exit(1);
  }
  final versionMatch = RegExp(r'version:\s*(\S+)');
  String? version;
  for (final line in pubspec.readAsLinesSync()) {
    final m = versionMatch.firstMatch(line);
    if (m != null) {
      version = m.group(1)?.trim();
      break;
    }
  }
  if (version == null) {
    stderr.writeln('Could not find version in pubspec.yaml');
    exit(1);
  }
  final out = File('lib/utils/app_version.g.dart');
  out.writeAsStringSync(
    "// Generated by tool/version_gen.dart – do not edit.\n"
    "part of 'config.dart';\n\n"
    "const String currentAppVersion = '$version';\n",
  );
  print('Wrote currentAppVersion = $version to lib/utils/app_version.g.dart');
}
